### ISSUE TITLE
为啥换自己的图片不行？

### ISSUE THREAD

**Issue by AnkerLeng** [JeffTrain/face-swap#1]

**Comment by AnkerLeng** [comment]
![image](https://user-images.githubusercontent.com/15144679/65563628-cc6ac980-df7c-11e9-89d2-ab53c3b6255a.png)

**Comment by Jeff-Tian** [comment]
有 bug，应该是一些区域越过边界了造成程序崩溃。你能分享一下用到的两张图片吗？我重现一下修掉这个bug。

谢谢你的反馈

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AnkerLeng** [comment]
![WechatIMG1046](https://user-images.githubusercontent.com/15144679/65680534-b7c82780-e089-11e9-8079-f926cbe05eff.jpeg)

到baidu照了几张都不ok

**Comment by Jeff-Tian** [comment]
@AnkerLeng 帮忙看下这个改动是不是已经把你的问题修复了：https://github.com/JeffTrain/face-swap/commit/dd155482956c5074163738699b7cfdb7b42e964f

我在本机测试通过：

## 测试矩阵

|环境|Python 版本|结果|
|---:|---:|---:|
|Windows|2.7|通过|
|Windows WSL|2.7|通过|

## 最终效果
和特朗普交换的效果不太好，但是程序成功运行了。

|源照片|目标照片|结果照片|
|-----:|-------:|-------:|
|![65680534-b7c82780-e089-11e9-8079-f926cbe05eff](https://raw.githubusercontent.com/JeffTrain/face-swap/master/tests/65680534-b7c82780-e089-11e9-8079-f926cbe05eff/65680534-b7c82780-e089-11e9-8079-f926cbe05eff.jpeg)|![唐纳德·特朗普](https://raw.githubusercontent.com/JeffTrain/face-swap/master/donald_trump.jpg)|![结果照片](https://raw.githubusercontent.com/JeffTrain/face-swap/master/tests/65680534-b7c82780-e089-11e9-8079-f926cbe05eff/result.jpg)|
